sudo: required

language: go

go: 
  - "1.x"

stages:
  - unit
  - integration

services:
  - docker

jobs:
  include:
    - &unit-setup
      stage: unit
      script:
        # Ensure result folder exists
        - mkdir -p $HOME/results/
        # Setup local certificate for testing
        - ./crt/make
        # Run simple go tests
        - go test -v -cover -coverprofile "${TRAVIS_OS_NAME}.out" ./core/...
        # Upload coverage results
        - go run ./test/gdrive.go
    - <<: *unit-setup
      os: osx
      before_script:
        # OSX comes with a user limit for number of open files
        - ulimit -n 10000
    - <<: *unit-setup
      os: windows

    - stage: integration
      env:
        # Specifies the kubernetes version.
        - KUBERNETES_VERSION=v1.10.0
        # This moves Kubernetes specific config files.
        - CHANGE_MINIKUBE_NONE_USER=true
      before_script:
        # Setup minikube for ci enviroment.
        - ./containers/ci/minikube
      script:
        # Deploy multiple duplicated of this container onto minikube.
        - ./containers/kube/deploy
        # Setup local certificate for testing
        - ./crt/make
        # Run all test interacting with the cluster
        - ./containers/ci/test
        # Clean everything from the minikube.
        - ./containers/kube/clean
        # Print all coverage results from cache
        - ls $HOME/results/
