sudo: required

language: go

go: 
  - "1.x"

stages:
  - unit
  - integration

services:
  - docker

notifications:
  webhooks: https://coveralls.io/webhook

definitions:
  coveralls: &coveralls
    go get github.com/mattn/goveralls && goveralls -coverprofile="coverage.out" -service=travis-ci -repotoken $COVERALLS_TOKEN
  
  codecov: &codecov
    bash <(curl -s https://codecov.io/bash)

  unit-setup: &unit-setup
      stage: unit
      script:
        # Setup local certificate for testing
        - ./crt/make
        # Run simple go tests
        - go test -v -cover -coverprofile "coverage.out" ./core/...
        - *coveralls
        - *codecov

jobs:
  include:
    - <<: *unit-setup
    - <<: *unit-setup
      os: osx
      before_script:
        # OSX comes with a user limit for number of open files
        - ulimit -n 10000
#    - <<: *unit-setup
#      os: windows

    - stage: integration
      env:
        # Set the Go os variable to javascript.
        - GOOS=js
        # Set the go architecture to wasm.
        - GOARCH=wasm
        # Set the wasm nodejs executor to path.
        - PATH="$PATH:$(go env GOROOT)/misc/wasm"
      before_script:
        # Setup minikube for ci enviroment.
        - ./containers/ci/minikube
      script:
        # Deploy multiple duplicated of this container onto minikube.
        - ./containers/kube/deploy
        # Setup local certificate for testing
        - ./crt/make
        # Run all test interacting with the cluster
        - ./containers/ci/test
        # Clean everything from the minikube.
        - ./containers/kube/clean
        - *coveralls
        - *codecov
    - stage: integration
      env:
        # Specifies the kubernetes version.
        - KUBERNETES_VERSION=v1.10.0
        # This moves Kubernetes specific config files.
        - CHANGE_MINIKUBE_NONE_USER=true
      before_script:
        # Setup minikube for ci enviroment.
        - ./containers/ci/minikube
      script:
        # Deploy multiple duplicated of this container onto minikube.
        - ./containers/kube/deploy
        # Setup local certificate for testing
        - ./crt/make
        # Run all test interacting with the cluster
        - ./containers/ci/test
        # Clean everything from the minikube.
        - ./containers/kube/clean
        - *coveralls
        - *codecov
