#!/bin/bash
kubectl create -f ./containers/kube/service.json
kubectl create -f ./containers/kube/endpoint.json
kubectl create -f ./containers/kube/pod.json
kubectl create -f ./containers/kube/podService.json
kubectl get services sip