#!/bin/bash

# Wait for deployed application to be ready.
JSONPATH='{.metadata.name}:{.status.availableReplicas}'; until kubectl get deployments sip -o jsonpath="$JSONPATH" 2>&1 | grep -q "sip:10"; do sleep 1; done

# Fetch the service port
SIP_PORT="$(kubectl get services sip -o jsonpath='{.spec.ports[0].nodePort}' 2>&1)"
SIP_HOST="$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')"
SIP_URL="https://${SIP_HOST}:${SIP_PORT}"
echo "home response: ${SIP_URL}"
curl -k "${SIP_URL}"
echo "index response: ${SIP_URL}/index"
curl -k "${SIP_URL}/index"
